import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config({ path: '.env' });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing env vars');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const facts = [
  { title: 'El túnel subterráneo de la Merced', text: 'Se rumora que existe un túnel colonial secreto que conecta el complejo religioso de La Merced con otras iglesias del centro histórico de Cali, usado antiguamente por los monjes.', city: 'Cali', category: 'Misterio', tags: ['historia', 'colonial'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Cali fue capital de Colombia', text: 'Durante una breve época en el siglo XIX, debido a las guerras civiles, Cali funcionó de facto como la sede del gobierno nacional mientras el presidente se resguardaba en la ciudad.', city: 'Cali', category: 'Historia', tags: ['nacional', 'siglo XIX'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'La estatua que mira al mar', text: 'A diferencia de otras estatuas de conquistadores, el monumento a Sebastián de Belalcázar está apuntando con su mano derecha hacia el Océano Pacífico, indicando la ruta hacia Buenaventura.', city: 'Cali', category: 'Monumentos', tags: ['arte', 'belalcázar'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El origen del "Mirá ve"', text: 'Esta clásica expresión caleña es una redundancia verbal heredada de formas del español andaluz, que se quedó arraigada exclusivamente en el Valle del Cauca para llamar la atención.', city: 'Cali', category: 'Cultura', tags: ['idioma', 'caleñismos'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'La primera luz eléctrica', text: 'Cali fue la segunda ciudad de Colombia en tener alumbrado público eléctrico (en 1910), gracias a la creación de la Compañía de Luz Eléctrica que usaba el cauce del río Cali.', city: 'Cali', category: 'Desarrollo', tags: ['modernidad', 'río cali'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El puente de los amantes', text: 'El Puente Ortiz no solo fue el primer puente de ladrillo, sino que en el siglo XX era el principal punto de encuentro a escondidas para los enamorados de diferentes clases sociales.', city: 'Cali', category: 'Romance', tags: ['puente ortiz', 'historia'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El diablo de las 3 Cruces', text: 'Antes de las 3 Cruces de cemento que conocemos hoy, en 1837 se plantaron tres cruces de guadua para encerrar al demonio "Buziraco" que traía pestes a la ciudad.', city: 'Cali', category: 'Mito', tags: ['buziraco', 'cerro'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El reloj de La Ermita', text: 'El gigantesco reloj musical de la iglesia La Ermita fue construido en Holanda y programado originalmente para tocar el Ave María cada hora en punto.', city: 'Cali', category: 'Arquitectura', tags: ['ermita', 'holanda'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Un zoológico de talla mundial', text: 'El Zoológico de Cali ha sido calificado constantemente entre los 3 mejores de toda América Latina gracias a su modelo de inmersión sin rejas y conservación.', city: 'Cali', category: 'Naturaleza', tags: ['fauna', 'parques'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'La maceta del padrino', text: 'Cali es el único lugar en el mundo donde los ahijados reciben cada 29 de junio una "Maceta": un palo de maguey adornado con dulces de alfeñique en forma de animales.', city: 'Cali', category: 'Tradición', tags: ['dulces', 'patrimonio'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Hacienda El Paraíso', text: 'La hacienda donde ocurre la famosa novela "María" de Jorge Isaacs, aún conserva los rosales y el cuarto exacto que describe el autor en el libro más leído del romanticismo latinoamericano.', city: 'El Cerrito', category: 'Literatura', tags: ['novela', 'maría'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Los 7 Ríos de Cali', text: 'Cali tiene el privilegio geográfico de ser atravesada por 7 ríos diferentes (Cali, Cauca, Pance, Meléndez, Lili, Cañaveralejo y Aguacatal).', city: 'Cali', category: 'Geografía', tags: ['ríos', 'agua'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El origen de la Feria', text: 'La Feria de Cali no nació para celebrar la salsa, sino que se creó en 1957 como un evento taurino y ganadero para devolverle el ánimo a la ciudad tras una trágica explosión.', city: 'Cali', category: 'Festivales', tags: ['feria', 'historia'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Salsa a 45 RPM', text: 'El ritmo rápido de la salsa caleña nació de un "error" intencional: los DJs de los años 70 ponían los discos de 33 RPM a 45 RPM para que la gente tuviera que mover los pies más rápido.', city: 'Cali', category: 'Música', tags: ['salsa', 'baile'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El falso Macondo', text: 'Aunque Macondo está inspirado en la costa caribe, gran parte de la magia literaria de Colombia tuvo su chispa en Cali con el "Grupo de Cali", creadores del Gótico Tropical.', city: 'Cali', category: 'Cine', tags: ['caliwood', 'literatura'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Grito de Independencia', text: 'Cali firmó su propia acta de independencia el 3 de julio de 1810, adelantándose por 17 días al famoso grito del 20 de julio en Bogotá.', city: 'Cali', category: 'Historia', tags: ['independencia', 'revolución'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'La verdadera Lulada', text: 'A diferencia del jugo, la verdadera lulada caleña jamás se mete a la licuadora; el lulo debe ser apachurrado a mano para que conserve su textura y trozos cítricos.', city: 'Cali', category: 'Gastronomía', tags: ['bebidas', 'lulo'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El Túnel Mundialista', text: 'Con casi un kilómetro de longitud por debajo del río, el túnel peatonal y vial construido para los Juegos Mundiales de 2013 es el más largo dentro de una ciudad en Colombia.', city: 'Cali', category: 'Infraestructura', tags: ['bulevar', 'túnel'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Mermelada en Totuma', text: 'El Manjar Blanco valluno tradicionalmente se envasa y sirve en una "totuma", que es la corteza seca del fruto del árbol de mate, una herencia directa de las culturas indígenas.', city: 'Valle del Cauca', category: 'Gastronomía', tags: ['dulces', 'totumo'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El Cholado sanador', text: 'El cholado nació en el municipio de Jamundí en los años 60. Originalmente no era un dulce, sino un remedio de lulo, limón y panela para curar la resaca de los hombres del pueblo.', city: 'Jamundí', category: 'Gastronomía', tags: ['cholado', 'curiosidad'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Las Novias del Gato', text: 'El Gato de Tejada estuvo solo durante 10 años hasta que en 2006 la ciudad le trajo "novias", esculturas de gatas intervenidas por diferentes artistas que ahora adornan el río.', city: 'Cali', category: 'Arte', tags: ['gato', 'río cali'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Un Museo en Resistencia', text: 'El Museo La Tertulia, fundado en 1956, comenzó como un club de lectura secreto para artistas y pensadores que buscaban refugio durante la violenta dictadura de la época.', city: 'Cali', category: 'Arte', tags: ['museo', 'tertulia'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Capital Deportiva', text: 'Cali es la única ciudad de Colombia, y de las pocas en América, en haber albergado unos Juegos Panamericanos (1971) y unos World Games (2013).', city: 'Cali', category: 'Deportes', tags: ['panamericanos', 'world games'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'La Platanera del Pacífico', text: 'El "chontaduro", apodado el huevo vegetal por sus proteínas, es vendido exclusivamente por mujeres afrodescendientes llamadas "platoneras", quienes mantienen viva esta tradición ancestral.', city: 'Cali', category: 'Cultura', tags: ['chontaduro', 'afro'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Mariposario Andoke', text: 'Cali alberga un inmenso mariposario a cielo abierto llamado Andoke, donde existe un mapa de Colombia a gran escala hecho completamente con vegetación viva.', city: 'Cali', category: 'Naturaleza', tags: ['mariposas', 'andoke'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Avistamiento Mundial', text: 'Los bosques nublados del Kilómetro 18 en la salida al mar son uno de los 5 mejores lugares del planeta para la observación de aves raras y endémicas (Birdwatching).', city: 'Cali', category: 'Naturaleza', tags: ['aves', 'km18'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'El Pandebono original', text: 'Se cuenta que el Pandebono toma su nombre de la antigua Hacienda El Bono, donde el pan que hacían se vendía gritando "¡Pan del Bono!" en las calles.', city: 'Dagua', category: 'Gastronomía', tags: ['pandebono', 'origen'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Cristo Rey, una hazaña', text: 'La estatua de Cristo Rey pesa 464 toneladas. Para construirla en 1953, los materiales tuvieron que subirse a lomo de mula por senderos empinados, sin vías vehiculares.', city: 'Cali', category: 'Monumentos', tags: ['cristo rey', 'construcción'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Champús con hojas', text: 'El ingrediente secreto que le da el sabor astringente y único al Champús vallecaucano son las hojas de naranjo agrio, usadas desde la época prehispánica.', city: 'Valle del Cauca', category: 'Gastronomía', tags: ['bebidas', 'indígena'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() },
  { title: 'Arquitectura Calima', text: 'Antes de la llegada de los españoles, el Valle del Cauca era habitado por la cultura Calima, quienes dominaban la metalurgia de oro puro siglos antes que cualquier otra civilización en Europa.', city: 'Valle del Cauca', category: 'Historia', tags: ['calima', 'oro'], status: 'published', show_in_home: true, show_in_pa_que_sepas: true, published_at: new Date().toISOString() }
];

async function run() {
  console.log('Inserting 30 curious facts...');
  const { data, error } = await supabase.from('curious_facts').insert(facts);
  if (error) {
    console.error('Error inserting facts:', error);
  } else {
    console.log('Successfully inserted 30 curious facts into Supabase!');
  }
}

run();
