export const COLOMBIAN_CITIES = [
    "Bogotá D.C., Cundinamarca",
    "Medellín, Antioquia",
    "Cali, Valle del Cauca",
    "Barranquilla, Atlántico",
    "Cartagena, Bolívar",
    "Cúcuta, Norte de Santander",
    "Bucaramanga, Santander",
    "Pereira, Risaralda",
    "Santa Marta, Magdalena",
    "Ibagué, Tolima",
    "Pasto, Nariño",
    "Manizales, Caldas",
    "Neiva, Huila",
    "Villavicencio, Meta",
    "Armenia, Quindío",
    "Valledupar, Cesar",
    "Montería, Córdoba",
    "Sincelejo, Sucre",
    "Popayán, Cauca",
    "Tunja, Boyacá",
    "Riohacha, La Guajira",
    "Florencia, Caquetá",
    "Yopal, Casanare",
    "Quibdó, Chocó",
    "Arauca, Arauca",
    "San Andrés, San Andrés y Providencia",
    "Leticia, Amazonas",
    "Mocoa, Putumayo",
    "San José del Guaviare, Guaviare",
    "Mitú, Vaupés",
    "Puerto Carreño, Vichada",
    "Inírida, Guainía",
    "Soacha, Cundinamarca",
    "Bello, Antioquia",
    "Palmira, Valle del Cauca",
    "Soledad, Atlántico",
    "Buenaventura, Valle del Cauca",
    "Barrancabermeja, Santander",
    "Tuluá, Valle del Cauca",
    "Dosquebradas, Risaralda",
    "Envigado, Antioquia",
    "Itagüí, Antioquia",
    "Girón, Santander",
    "Zipaquirá, Cundinamarca",
    "Sogamoso, Boyacá",
    "Buga, Valle del Cauca",
    "Duitama, Boyacá",
    "Cartago, Valle del Cauca",
    "Facatativá, Cundinamarca",
    "Fusagasugá, Cundinamarca",
    "Chía, Cundinamarca",
    "Malambo, Atlántico",
    "Rionegro, Antioquia",
    "Floridablanca, Santander",
    "Apartadó, Antioquia",
    "Jamundí, Valle del Cauca",
    "Pitalito, Huila",
    "Lorica, Córdoba",
    "Turbo, Antioquia",
    "Magangué, Bolívar",
    "Maicao, La Guajira",
    "Ipiales, Nariño",
    "Ciénaga, Magdalena"
].sort();
